# Generated by Django 6.0.2 on 2026-07-20 22:37

import config.uploads
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="toolkit",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="toolkit",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                editable=False,
                upload_to=config.uploads.toolkit_preview_path,
            ),
        ),
        migrations.AddField(
            model_name="toolkit",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="toolkits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="toolkit",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=config.uploads.toolkit_pdf_path,
                validators=[config.uploads.validate_pdf],
            ),
        ),
    ]
