# Generated by Django 6.0.2 on 2026-07-08 01:28

import config.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to=config.uploads.post_image_path
            ),
        ),
    ]
