# Generated by Django 6.0.2 on 2026-07-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this post from the public feed. Only you can see hidden posts.",
            ),
        ),
    ]
