# Generated by Django 6.0.2 on 2026-07-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_category_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="This post is visible to everyone. Turn this off to keep it private.",
                verbose_name="Is Public",
            ),
        ),
    ]
