# Generated by Django 6.0.2 on 2026-07-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_alter_post_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="Hide your username and avatar on this post.",
                verbose_name="Post anonymously",
            ),
        ),
    ]
