# Generated by Django 6.0.2 on 2026-07-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_set_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("young_adult", "Young Adult"),
                    ("parent", "Parent"),
                    ("caregiver", "Caregiver"),
                    ("educator", "Educator"),
                    ("mental_health_professional", "Mental Health Professional"),
                    ("healthcare_professional", "Healthcare Professional"),
                    ("researcher", "Researcher"),
                    ("advocate", "Advocate"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
