# Generated by Django 6.0.2 on 2026-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remap_role_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="workos_user_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
