# Generated by Django 6.0.2 on 2026-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_workos_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="site_role",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
